### ISSUE TITLE
Compilation error occurred in diff_gaussian_rasterization

### ISSUE THREAD

**Issue by StringerYwh00** [KU-CVLAB/RAIN-GS#13]
![批注 2024-05-21 131139](https://github.com/KU-CVLAB/RAIN-GS/assets/139751833/2ed0cf45-6cbe-4a58-9628-7d92c792c2e7)
Your setup file seems incomplete

**Comment by StringerYwh00** [comment]
![image](https://github.com/KU-CVLAB/RAIN-GS/assets/139751833/8fbe76fc-057f-4e02-9ccf-20ae024e6253)

**Comment by crepejung00** [comment]
Hi,
sorry for the late response.

We think this issue is similar to a previous problem mentioned here #4.
All of our experiments and implementations were done in the environment of ubuntu :20.04, python: 3.8.16, and cuda:12.1. The setup.py you have mentioned is only for jit-compilation of the cuda rasterizer and it did not cause a problem in our environment. 
Could you please provide us which environment you are working on? (ubuntu, cuda)

Thanks,
Jaewoo.

**Comment by Yuhuoo** [comment]
I also have encountered the problem:
                                                                                                                                   
```
Pip subprocess output:
Processing ./submodules/diff_gaussian_rasterization
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/data1/GaoAo/code/RAIN-GS/submodules/diff_gaussian_rasterization/setup.py", line 3, in <module>
          from torch.utils.cpp_extension import CUDAExtension, BuildExtension, _get_build_directory, load
        File "/data1/GaoAo/software/anaconda3/envs/rain_gaussian_splatting/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 28, in <module>
          from pkg_resources import packaging  # type: ignore[attr-defined]
      ImportError: cannot import name 'packaging' from 'pkg_resources' (/data1/GaoAo/software/anaconda3/envs/rain_gaussian_splatting/lib/python3.8/site-packages/pkg_resources/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```
The environment  I used is : ubuntu :20.04, python: 3.8.16, and cuda:12.1. and the details of config are:

```
name: rain_gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.7
  - python=3.8.16
  - pip=22.3.1
  - pytorch=2.1.0
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - tqdm
  - pip:
    - submodules/diff_gaussian_rasterization
    - submodules/simple-knn
```

**Comment by Yuhuoo** [comment]
I have solved the problem by reinstall pytorch.

**Comment by Bonnie768** [comment]
> 我已经通过重新安装 pytorch 解决了这个问题。

Hello, may I ask what versions of your installation package are?
