### ISSUE TITLE
RuntimeError: Function _RasterizeGaussiansBackward returned an invalid gradient at index 2 - got [0, 0, 3] but expected shape compatible with [0, 16, 3]

### ISSUE THREAD

**Issue by jiangyijin** [KU-CVLAB/RAIN-GS#17]
I encountered a problem; how can I solve it?
Traceback (most recent call last):
  File "/data/RAIN-GS/train.py", line 295, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations ,args.save_iterations, args.checkpoint_iterations ,args.start_checkpoint, args.debug_from, args.__dict__)
  File "/data/RAIN-GS/train.py", line 115, in training
    loss.backward()
  File "/home/ubuntu/anaconda3/envs/3dgs/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/ubuntu/anaconda3/envs/3dgs/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function _RasterizeGaussiansBackward returned an invalid gradient at index 2 - got [0, 0, 3] but expected shape compatible with [0, 16, 3]

**Comment by crepejung00** [comment]
Hi,
We currently found that there are some minor code errors in our current version, and we are refactoring the code.
Sorry for the inconvenience and we will note you when the codes are fixed.

**Comment by shinobiultra** [comment]
Still doesn't work.
